version: 1

update_configs:

# Source

  - package_manager: "dotnet:nuget"
    directory: "/src/Application"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:minor"

  - package_manager: "dotnet:nuget"
    directory: "/src/Domain"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:minor"

  - package_manager: "dotnet:nuget"
    directory: "/src/Infrastructure"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
    ignored_updates:
      - match:
         dependency_name: "Simple.OData.Client"


  - package_manager: "dotnet:nuget"
    directory: "/src/OfficeEntry.Plugins"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:minor"

  - package_manager: "dotnet:nuget"
    directory: "/src/WebApp"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:minor"

# Tests

  - package_manager: "dotnet:nuget"
    directory: "/tests/Application.UnitTests"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:minor"

  - package_manager: "dotnet:nuget"
    directory: "/tests/Domain.UnitTests"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:minor"

  - package_manager: "dotnet:nuget"
    directory: "/tests/Infrastructure.IntegrationTests"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
