version: 1

update_configs:

# Source

  - package_manager: "dotnet:nuget"
    directory: "/src/Application"
    update_schedule: "live"
  
  - package_manager: "dotnet:nuget"
    directory: "/src/Domain"
    update_schedule: "live"

  - package_manager: "dotnet:nuget"
    directory: "/src/Infrastructure"
    update_schedule: "live"

  - package_manager: "dotnet:nuget"
    directory: "/src/OfficeEntry.Plugins"
    update_schedule: "live"

  - package_manager: "dotnet:nuget"
    directory: "/src/WebApp"
    update_schedule: "live"

# Tests

  - package_manager: "dotnet:nuget"
    directory: "/tests/Application.UnitTests"
    update_schedule: "live"

  - package_manager: "dotnet:nuget"
    directory: "/tests/Domain.UnitTests"
    update_schedule: "live"

  - package_manager: "dotnet:nuget"
    directory: "/tests/Infrastructure.IntegrationTests"
    update_schedule: "live"