//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEntry.Plugins
{

	[System.Runtime.Serialization.DataContractAttribute()]
	public enum gc_accessrequest_gc_approvalstatus
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approved = 948160001,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cancelled = 948160003,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Declined = 948160002,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pending = 948160000,
	}
}