//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEntry.Plugins
{

	[System.Runtime.Serialization.DataContractAttribute()]
	public enum gc_accessrequest_gc_accessreason
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Criticalwork = 948160000,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 948160004,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pickupofficeequipment = 948160003,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Regularwork = 948160002,
	}
}