//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEntry.Plugins
{

	[System.Runtime.Serialization.DataContractAttribute()]
	public enum gc_accessrequest_StatusCode
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
}